---
output: 
  pdf_document:
    fig_crop: no
header-includes:
  - \usepackage[brazil, english, portuguese]{babel}
  - \usepackage[utf8]{inputenc}
  - \usepackage[T1]{fontenc}
  - \usepackage[fixlanguage]{babelbib}
  - \usepackage{times}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, 
  message = FALSE,
  warning = FALSE,
  fig.align = "center", fig.height = 3, fig.width = 5
  )
options(
  OutDec = ",", 
  digits = 3, 
  knitr.table.format = "latex", 
  xtable.comment = FALSE
  )
```

Obs: Caio gosta de legendas em Figuras e Tabelas: embaixo para figuras e em cima para tabelas.

## Introdução

Apresentar o conjunto de dados: o que são, como foram obtidos e onde obter. Explicar qual é o objetivo do estudo. Mencionar a técnica (modelo) a ser usado e uma referência para ele.

## Análise descritiva



## Análise Inferencial

- especificar o modelo e explicar seus termos.
- análise(s) de resíduo(s)
- hipóteses de interesse (O NÍVEL DE SIGNIFICÂNCIA DEVE SER ESPECIFICADO NO RELATÓRIO)
-análise de multicolinearidade
- modelagem a heterocedasticidade
- gráficos e comentários
- deverão   ser   usadas   asmetodologias constantes na questão
- caso o modelo usado não se adeque bem   aos   dados,   comentários   a   respeito   deverão   ser   feitos,   mencionando   que   outras metodologias devem ser utilizadas (não, necessariamente, precisa ser dito quais)


## Conclusão

Resumir se os modelos se ajustaram bem aos dados, dizer qual foi o melhor/menos pior, o que esse modelo indicou de explicação/conclusão em termos do problema.

## Referências
