---
title: "coelhos"
author: "Leticia Bettini Infante"
date: "4 de junho de 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
dados_coelho <- read.table("coelhos.txt")
names(dados_coelho) <- c("idade", "peso")

#quero saber se a idade influencia no peso do olho

plot(dados_coelho$idade, dados_coelho$peso)

#modelo linear
m1 <- lm(peso ~ idade, data = dados_coelho)
c1 <- c(AIC(m1), BIC(m1))
s <- summary(m1)
s$coefficients
R21 <- c(s$r.squared, s$adj.r.squared)
R21

#graficos para analise de residuo modelo linear
par(mfrow=c(2,2))
plot(resid(m1))
plot(resid(m1) ~ predict(m1))
hist(resid(m1))
qqnorm(resid(m1))

#modelo quadratico
idade2 <- (dados_coelho$idade)^2
m2 <- lm(peso ~ idade + idade2, data = dados_coelho)
c2 <- c(AIC(m2), BIC(m2))
s2 <- summary(m2)
s2$coefficients
R22 <- c(s2$r.squared, s2$adj.r.squared)
R22

#graficos para analise de residuo modelo quadratico
par(mfrow=c(2,2))
plot(resid(m2))
plot(resid(m2) ~ predict(m2))
hist(resid(m2))
qqnorm(resid(m2))


#estatisticas de comparacao de teste
aic <- c(AIC(m1), AIC(m2))
bic <- c(BIC(m1), BIC(m2))
comparacao <- as.data.frame(rbind(aic, bic))
names(comparacao) <- c("linear", "quadratico")
comparacao

#teste da razao de verossimilhanca
trv <- (-2*(as.numeric(logLik(m1)) - as.numeric(logLik(m2))))
pvalor <- 1-pchisq(trv, df=1)
pvalor

```

